# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked, A unique name
  name: plugin-apphub
spec:
  enabled: true
  requires: ">=2.21.0"
  author:
    name: 星风之痕
    website: hhttps://github.com/springai/halo-plugin-apphub
  logo: logo.svg
  homepage: https://github.com/springai/halo-plugin-apphub#readme
  repo: https://github.com/springai/halo-plugin-apphub
  issues: https://github.com/springai/halo-plugin-apphub/issues
  configMapName: plugin-apphubs-configmap
  settingName: plugin-apphubs-settings
  displayName: "plugin-apphub"
  description: "Halo应用舱后台管理"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/springai/halo-plugin-apphub/blob/main/LICENSE"
